stages:
  - build
  - test
  - deploy

jobBuild:
  stage: build
  script:
    - echo "Job build eseguito"

jobTest:
  image: cypress/base:10
  stage: test
  script:
    - cd tests
    - npm install
    - npm run runHeadless

jobDeploy:
  stage: deploy
  script:
    - echo "Job deploy eseguito"  