stages:
  - build
  - test
  - deploy
jobBuild:
  stage: build
  script:
    - echo "Job build eseguito"
jobTest:
  stage: test
  script:
    - echo "Job test eseguito"
jobDeploy:
  stage: deploy
  script:
    - echo "Job deploy eseguito"  